### ISSUE TITLE
Browse button looks off on FF 35.0.1 (Windows 7)

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/document_tool#1]
When I edit the doc, the "Browse" button looks off on FF 35.0.1 (Windows 7).
![capture](https://cloud.githubusercontent.com/assets/1034174/6011023/7966d180-aaec-11e4-8cbd-f11e045b4a76.PNG)

**Comment by stevenolen** [comment]
I just tested in firefox 34.0.5 and it looks to be fixed now (the button adds an ellipses) per a suggestion on  (this stackoverflow)[http://stackoverflow.com/questions/22049739/fix-for-firefox-file-input-using-bootstrap-3-1]

@ctrance could you re-test quick and close if it's working? thanks!

**Comment by ctrance** [comment]
fixed
