### ISSUE TITLE
Downloading word doc on FF 35.0.1 (Windows 7) doesn't recognize the file type

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/document_tool#2]
I downloaded "Alyssa LastName1.docx" using FF 35.0.1 (Windows 7), but the file type became "unknown" after. On chrome, the downloaded file is still word doc.
![capture](https://cloud.githubusercontent.com/assets/1034174/6011110/5b83ae12-aaed-11e4-9898-5329f3873d18.PNG)

**Comment by stevenolen** [comment]
Related to https://github.com/ohmage/server/issues/852, I think I may have re-deployed the wrong version before @ctrance tested.  Will test.

**Comment by stevenolen** [comment]
@ctrance I redeployed what is definitely the corrected server build now and tested on Firefox 34.0.5 on mac 10.10.  Could you retest on windows? thanks!

**Comment by ctrance** [comment]
fixed
