### ISSUE TITLE
Add New doc form gets pre-filled with previous doc info

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/document_tool#3]
On FF, when I view other doc on its modal prior to adding new doc the form gets pre-filled with previous doc info. On Chrome, only 'Campaign' field gets pre-filled with previous doc info.
![capture](https://cloud.githubusercontent.com/assets/1034174/6024754/57891726-ab82-11e4-8a4c-99ba538afcb3.PNG)

**Comment by stevenolen** [comment]
should be fixed now, tested in FF24 and chrome and no fields are erroneously pre-filled.

**Comment by ctrance** [comment]
fixed
