### ISSUE TITLE
Selecting "All" from the show entries drop down shows blank result list

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/document_tool#4]
I was testing the show # entries drop down but selecting "All" doesn't show all docs.
![capture](https://cloud.githubusercontent.com/assets/1034174/6024891/7fbd1ff2-ab83-11e4-91f9-4217afea0ce3.PNG)

**Comment by stevenolen** [comment]
@ctrance should be fixed now! tested in FF24 and chrome

**Comment by ctrance** [comment]
@stevenolen - I have to scroll to the right to access the buttons on FF if I view all, unlike Chrome.
![capture](https://cloud.githubusercontent.com/assets/1034174/6030966/3afd82a8-abb0-11e4-8da5-d4318aeb69c6.PNG)

**Comment by stevenolen** [comment]
it looks like FF wont wrap at words like chrome will.  this is an issue with datatables and how long our test doc names are, I'm going to let this one go since our users shouldn't experience this with a typical non-test setup.
