### ISSUE TITLE
"Description" fields on edit mode gets pre-filled incorrectly 

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/document_tool#5]
I edited the doc's description then saved the changes. I got the successful saving message but when I click edit button again the description field didn't get updated. Maybe it's just a display issue since I got the successful message upon saving the edit. Encountered on both Chrome and FF.

![capture](https://cloud.githubusercontent.com/assets/1034174/6025276/feea60c6-ab85-11e4-9cd5-2d4ea64f4d4a.PNG)

**Comment by stevenolen** [comment]
@ctrance should be fixed in FF and chrome now!

**Comment by ctrance** [comment]
@stevenolen - 'mwf.cathy' is editing its own doc Jellyfish.jpg to test the Description field but I'm getting 'general server error' when I update. Can you please check?

**Comment by stevenolen** [comment]
@ctrance. that's odd, same db problem as before, should be fixed for now!

**Comment by ctrance** [comment]
This issue has been fixed.
