### ISSUE TITLE
Restricted class member doesn't see shared document in the class

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/document_tool#6]
User mwf.cathy is a privileged member of "cathy test" class and added a private doc to the class with private state. "ctrance1" a privileged member of the said class can see the doc but "ctrance2" a restricted member cannot see the doc.

**Comment by stevenolen** [comment]
that's working as intended, "private" state works similarly to how survey responses work in ohmage: when a document is set as "private" the owner of the content in addition to supervisors in attached classes/campaigns can see it, but unprivileged users cannot. should maybe even have a test case for this :+1:

**Comment by ctrance** [comment]
@stevenolen - Got it, I'll add this to the test case.
